### ISSUE TITLE
Quickmail Failed when Attempted Install on Moodle 4.5

### ISSUE THREAD

**Issue by bgatwood** [lsuonline/lsuce-block_quickmail#95] opened 2024-10-18 23:14 UTC
I am using Moodle 4.5 on HostGator, Moodle installed using Sotaculous installer on a shared site.

When I  download and install Quickmail, I received the following  error:

Exception - Undefined constant "MESSAGE_DEFAULT_LOGGEDIN"

More information about this error

Debug info:
Error code: generalexceptionmessage×Dismiss this notification
Stack trace:
line 30 of /blocks/quickmail/db/messages.php: Error thrown
line 692 of /lib/messagelib.php: call to require()
line 419 of /lib/messagelib.php: call to message_get_providers_from_file()
line 623 of /lib/upgradelib.php: call to message_update_providers()
line 1077 of /lib/upgradelib.php: call to upgrade_component_updated()
line 653 of /lib/upgradelib.php: call to upgrade_plugins_blocks()
line 1937 of /lib/upgradelib.php: call to upgrade_plugins()
line 719 of /admin/index.php: call to upgrade_noncore()

Possibly this will be handled as a matter of course when Quickmail is formally upgraded to be compatible with 4.5 as I see it says it is for only up to 4.4.

**Comment by aspark21** [comment] 2024-10-19 10:25
Duplicate of #90 with fix in #93

**Comment by aspark21** [comment] 2024-10-30 17:10
Fixed fixed in https://github.com/lsuonline/lsuce-block_quickmail/commit/0c9c9da980ad403bb16cdbe0ec68e2c3578e4cca

**Closed** 2024-10-30 19:07 UTC
